# Generated by Django 3.2.7 on 2021-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='colour',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
