# Generated by Django 3.2.7 on 2021-09-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_phone_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='storage',
            field=models.IntegerField(default=None, max_length=20),
        ),
    ]
