# Generated by Django 3.2.7 on 2021-09-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_phone_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='grade',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
