# Generated by Django 3.2.7 on 2021-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_phone_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.IntegerField(default=None),
        ),
    ]
