# Generated by Django 3.2.7 on 2021-09-17 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210917_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.phonecolour'),
        ),
    ]
