# Generated by Django 3.2.7 on 2021-09-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210917_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.phonegrade'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.phonestorage'),
        ),
    ]
