# Generated by Django 3.2.7 on 2021-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210917_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='IMEI',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
