# Generated by Django 3.2.7 on 2021-09-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_phone_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='IMEI',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
