# Generated by Django 3.2.7 on 2021-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_phone_photourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
