# Generated by Django 3.2.7 on 2021-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_phone_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='IMEI',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
