# Generated by Django 3.2.7 on 2021-09-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210919_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='photo_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
