# Generated by Django 3.2.7 on 2021-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_phone_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
    ]
