# Generated by Django 3.2.7 on 2021-09-22 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_phone_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
