# Generated by Django 3.2.7 on 2021-09-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_phone_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
