# Generated by Django 3.2.7 on 2021-10-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_phone_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=9999)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
